-- Intentionally empty. Spring's ScriptUtils can't parse PostgreSQL
-- dollar-quoted blocks (see #404). Hibernate creates TIMESTAMPTZ
-- columns directly from Instant entity fields, so no migration runs here.
