export const OBJECT_TYPES = [
  {
    type: 'RAMP',
    label: 'Ramp',
    icon: 'accessible_forward',
    markerColor: '#2E7D32',
    environments: ['OUTDOOR', 'INDOOR'],
    issues: [
      { key: 'MISSING',                   label: 'Missing' },
      { key: 'TOO_STEEP',                 label: 'Too Steep' },
      { key: 'TOO_NARROW',                label: 'Too Narrow' },
      { key: 'MISSING_HANDRAIL',          label: 'Missing Handrail' },
      { key: 'NO_LANDING',                label: 'No Landing' },
      { key: 'SLIPPERY_SURFACE',          label: 'Slippery Surface' },
      { key: 'HANDRAIL_TOO_LOW',          label: 'Handrail Too Low' },
      { key: 'INSUFFICIENT_LANDING_AREA', label: 'Insufficient Landing Area' },
    ],
    measurements: [
      { key: 'slope_percent', label: 'Slope',  unit: '%',  accessible_max: 10 },
      { key: 'width_cm',      label: 'Width',  unit: 'cm', accessible_min: 100 },
      { key: 'height_cm',     label: 'Height', unit: 'cm' },
    ],
  },
  {
    type: 'ELEVATOR',
    label: 'Elevator',
    icon: 'elevator',
    markerColor: '#B02500',
    environments: ['OUTDOOR', 'INDOOR'],
    issues: [
      { key: 'MISSING',               label: 'Missing' },
      { key: 'OUT_OF_SERVICE',        label: 'Out of Service' },
      { key: 'DOOR_TOO_NARROW',       label: 'Door Too Narrow' },
      { key: 'CABIN_TOO_SMALL',       label: 'Cabin Too Small' },
      { key: 'NO_AUDIO',              label: 'No Audio' },
      { key: 'NO_GRAB_BAR',           label: 'No Grab Bar' },
      { key: 'INSUFFICIENT_LANDING',  label: 'Insufficient Landing' },
      { key: 'NO_BRAILLE',            label: 'No Braille' },
      { key: 'BUTTON_HEIGHT_INVALID', label: 'Button Height Invalid' },
      { key: 'INSUFFICIENT_LIGHTING', label: 'Insufficient Lighting' },
    ],
    measurements: [
      { key: 'door_width_cm',  label: 'Door Width',  unit: 'cm', accessible_min: 90 },
      { key: 'cabin_width_cm', label: 'Cabin Width', unit: 'cm', accessible_min: 120 },
      { key: 'cabin_depth_cm', label: 'Cabin Depth', unit: 'cm', accessible_min: 140 },
    ],
  },
  {
    type: 'SIDEWALK',
    label: 'Sidewalk',
    icon: 'directions_walk',
    markerColor: '#495F69',
    environments: ['OUTDOOR'],
    issues: [
      { key: 'MISSING',                   label: 'Missing' },
      { key: 'TOO_NARROW',                label: 'Too Narrow' },
      { key: 'SLIPPERY_SURFACE',          label: 'Slippery Surface' },
      { key: 'BLOCKED',                   label: 'Blocked' },
      { key: 'NO_TACTILE_PAVING',         label: 'No Tactile Paving' },
      { key: 'INSUFFICIENT_CLEARANCE',    label: 'Insufficient Clearance' },
      { key: 'UNEVEN_SURFACE',            label: 'Uneven Surface' },
      { key: 'UNRAMPED_LEVEL_DIFFERENCE', label: 'Unramped Level Difference' },
    ],
    measurements: [
      { key: 'height_cm', label: 'Curb Height', unit: 'cm', accessible_max: 15 },
      { key: 'width_cm',  label: 'Width',       unit: 'cm', accessible_min: 150 },
    ],
  },
  {
    type: 'DOOR',
    label: 'Door',
    icon: 'door_front',
    markerColor: '#8B6A00',
    environments: ['OUTDOOR', 'INDOOR'],
    issues: [
      { key: 'MISSING',               label: 'Missing' },
      { key: 'TOO_NARROW',            label: 'Too Narrow' },
      { key: 'HIGH_THRESHOLD',        label: 'High Threshold' },
      { key: 'STEP_AT_ENTRANCE',      label: 'Step at Entrance' },
      { key: 'NO_LEVER_HANDLE',       label: 'No Lever Handle' },
      { key: 'HEAVY_DOOR',            label: 'Heavy Door' },
      { key: 'NO_AUTOMATIC_DOOR',     label: 'No Automatic Door' },
      { key: 'NO_GLASS_MARKING',      label: 'No Glass Marking' },
      { key: 'HANDLE_HEIGHT_INVALID', label: 'Handle Height Invalid' },
      { key: 'INTERCOM_INACCESSIBLE', label: 'Intercom Inaccessible' },
    ],
    measurements: [
      { key: 'width_cm',            label: 'Width',            unit: 'cm', accessible_min: 90 },
      { key: 'threshold_height_cm', label: 'Threshold Height', unit: 'cm', accessible_max: 0.6 },
    ],
  },
  {
    type: 'STAIR',
    label: 'Stair',
    icon: 'stairs',
    markerColor: '#B65900',
    environments: ['OUTDOOR', 'INDOOR'],
    issues: [
      { key: 'MISSING',              label: 'Missing' },
      { key: 'TOO_NARROW',           label: 'Too Narrow' },
      { key: 'MISSING_HANDRAIL',     label: 'Missing Handrail' },
      { key: 'NO_LANDING',           label: 'No Landing' },
      { key: 'SLIPPERY_SURFACE',     label: 'Slippery Surface' },
      { key: 'RISER_TOO_HIGH',       label: 'Riser Too High' },
      { key: 'TREAD_TOO_SHALLOW',    label: 'Tread Too Shallow' },
      { key: 'NO_ANTI_SLIP',         label: 'No Anti-Slip' },
      { key: 'OPEN_RISERS',          label: 'Open Risers' },
      { key: 'IRREGULAR_STEPS',      label: 'Irregular Steps' },
      { key: 'MISSING_NOSING_STRIP', label: 'Missing Nosing Strip' },
    ],
    measurements: [
      { key: 'riser_cm', label: 'Riser Height', unit: 'cm', accessible_max: 16 },
      { key: 'tread_cm', label: 'Tread Depth',  unit: 'cm', accessible_min: 27 },
    ],
  },
  {
    type: 'PEDESTRIAN_CROSSING',
    label: 'Pedestrian Crossing',
    icon: 'traffic',
    markerColor: '#1565C0',
    environments: ['OUTDOOR'],
    issues: [
      { key: 'MISSING',              label: 'Missing' },
      { key: 'BLOCKED',              label: 'Blocked' },
      { key: 'NO_TACTILE_PAVING',    label: 'No Tactile Paving' },
      { key: 'NO_AUDIO_SIGNAL',      label: 'No Audio Signal' },
      { key: 'SIGNAL_TOO_SHORT',     label: 'Signal Too Short' },
      { key: 'NO_DROPPED_CURB',      label: 'No Dropped Curb' },
      { key: 'FADED_MARKINGS',       label: 'Faded Markings' },
      { key: 'NO_PEDESTRIAN_REFUGE', label: 'No Pedestrian Refuge' },
    ],
    measurements: [
      { key: 'signal_duration_sec',    label: 'Signal Duration',    unit: 's',  accessible_min: 15 },
      { key: 'crossing_width_cm',      label: 'Crossing Width',     unit: 'cm', accessible_min: 300 },
      { key: 'dropped_curb_height_cm', label: 'Dropped Curb Height', unit: 'cm', accessible_max: 1.3 },
    ],
  },
  {
    type: 'CURB_RAMP',
    label: 'Curb Ramp',
    icon: 'accessible',
    markerColor: '#6A4C00',
    environments: ['OUTDOOR'],
    issues: [
      { key: 'MISSING',            label: 'Missing' },
      { key: 'TOO_STEEP',          label: 'Too Steep' },
      { key: 'TOO_NARROW',         label: 'Too Narrow' },
      { key: 'NO_TACTILE_WARNING', label: 'No Tactile Warning' },
      { key: 'RAISED_LIP',         label: 'Raised Lip' },
    ],
    measurements: [
      { key: 'slope_percent', label: 'Slope',      unit: '%',  accessible_max: 8 },
      { key: 'width_cm',      label: 'Width',      unit: 'cm', accessible_min: 120 },
      { key: 'lip_height_cm', label: 'Lip Height', unit: 'cm', accessible_max: 1.3 },
    ],
  },
  {
    type: 'WASHROOM',
    label: 'Washroom',
    icon: 'wc',
    markerColor: '#00838F',
    environments: ['INDOOR'],
    issues: [
      { key: 'MISSING',                    label: 'Missing' },
      { key: 'TOO_NARROW',                 label: 'Too Narrow' },
      { key: 'NO_GRAB_BAR',                label: 'No Grab Bar' },
      { key: 'HIGH_THRESHOLD',             label: 'High Threshold' },
      { key: 'NO_ACCESSIBLE_STALL',        label: 'No Accessible Stall' },
      { key: 'INSUFFICIENT_TURNING_SPACE', label: 'Insufficient Turning Space' },
      { key: 'SINK_TOO_HIGH',              label: 'Sink Too High' },
      { key: 'NO_EMERGENCY_BUTTON',        label: 'No Emergency Button' },
    ],
    measurements: [
      { key: 'door_width_cm',      label: 'Door Width',      unit: 'cm', accessible_min: 90 },
      { key: 'turning_space_cm',   label: 'Turning Space',   unit: 'cm', accessible_min: 150 },
      { key: 'sink_height_cm',     label: 'Sink Height',     unit: 'cm', accessible_max: 85 },
      { key: 'grab_bar_height_cm', label: 'Grab Bar Height', unit: 'cm', accessible_min: 70 },
    ],
  },
  {
    type: 'ROOM_SIGN',
    label: 'Room Sign',
    icon: 'meeting_room',
    markerColor: '#5E35B1',
    environments: ['INDOOR'],
    issues: [
      { key: 'MISSING',               label: 'Missing' },
      { key: 'NO_BRAILLE',            label: 'No Braille' },
      { key: 'INSUFFICIENT_LIGHTING', label: 'Insufficient Lighting' },
      { key: 'LOW_CONTRAST',          label: 'Low Contrast' },
      { key: 'TEXT_TOO_SMALL',        label: 'Text Too Small' },
      { key: 'INVALID_HEIGHT',        label: 'Invalid Height' },
    ],
    measurements: [
      { key: 'mounting_height_cm', label: 'Mounting Height', unit: 'cm', accessible_min: 120, accessible_max: 160 },
      { key: 'text_height_mm',     label: 'Text Height',     unit: 'mm', accessible_min: 15 },
    ],
  },
]

export const OBJECT_TYPE_MAP = Object.fromEntries(OBJECT_TYPES.map(t => [t.type, t]))
